version: "3"

services:
  es01:
    hostname: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=_site_
    ulimits:
      memlock:
        soft: -1
        hard: -1
  postgres:
    hostname: postgres
    image: postgres:11-alpine
    env_file: 
      - ../engconfig/eng-schedule.env
    ports: 
      - "5432:5432"
  scheduler:
    build: engage_scheduler
    image: hack4laengage/engage_scheduler:latest
    depends_on:
      - "postgres"
    env_file: 
      - ../engconfig/eng-schedule.env
    links:
      - "postgres"
  