version: "3"

services: 
  rabbitmq:
    image: rabbitmq:3.8-rc-alpine
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    hostname: rabbitmq
    ports:
      - "5672:5672"
    logging: 
      driver: "none"
  redis:
    environment:
      - REDIS_PASSWORD=somepass
    image: redis:5-alpine
    hostname: redis
    command: "sh -c 'printenv REDIS_PASSWORD 2>&1 > ./redis_pass; sed -i \"1s/^/requirepass /\" ./redis_pass; redis-server ./redis_pass'; "
    ports: 
      - "6379:6379"
  celery_worker:
    build: engage_app
    image: hack4laengage/engage_celery:latest
    working_dir: /engage_app
    entrypoint: ./scripts/runworkerstest.sh
    links: 
      - rabbitmq
      - redis
    depends_on: 
      - rabbitmq
      - redis
    environment: 
      - RABBITMQ_URI=admin:mypass@rabbitmq:5672
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=somepass
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=somepass
      - POSTGRES_PORT=5432
      - SCHEDULER=tests
      - TASKS=tests.tasks
  celery_beat:
    build: engage_app
    image: hack4laengage/engage_celery:latest
    working_dir: /engage_app
    entrypoint: ./scripts/runbeats.sh
    links: 
      - rabbitmq
      - redis
      - celery_worker
    depends_on: 
      - rabbitmq
      - redis
      - celery_worker
    environment: 
      - RABBITMQ_URI=admin:mypass@rabbitmq:5672
      - REDIS_URI=redis:6379
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - SCHEDULER=tests
      - TASKS=tests.tasks
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=somepass
      - POSTGRES_PORT=5432
      - REDIS_PASSWORD=somepass
